name: Build and Deploy

on:
  repository_dispatch:
    types: [build-sveltekit]
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: 'Create env file'
        run: |
          echo "${{ secrets.API_URL }}" > .env

      - name: Build
        env:
          API_URL: ${{ secrets.API_URL }}

        run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
