name: Trigger Build

on:
  workflow_dispatch:
    inputs:
      build:
        description: 'Trigger a SvelteKit build'
        required: true
        default: 'true'

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Dispatch build-sveltekit event
      uses: peter-evans/repository-dispatch@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        repository: ${{ github.repository }}
        event-type: build-sveltekit
